import { strict as assert } from "node:assert";
import { test } from "node:test";
import { DeliveryTask } from "./delivery";
import { StagedProcess, processSupplyPhase } from "./process-supply";
import type { EntityId, ProcessRequirements, QueryRow, QuerySpec, WriteContext } from "../contracts";
const req: ProcessRequirements = { definition: "ale", version: 1, stationCatalog: "brew-station", phase: "waiting", inputs: [{ role: "grain", port: "kettle", material: "grain", quantity: 2, policy: "portion", disposition: "consume" }], stages: [{ id: "work", mode: "attended", durationSeconds: 1 }] };
const value = (station: EntityId) => ({ version: 2, definition: "ale", definitionVersion: 1, station, worker: null, stageIndex: 0, progressSeconds: 0, enteredTick: 0, phase: "waiting" as const, blockedReason: "" });
function run(processes: readonly EntityId[], lots: { id: EntityId; container: EntityId; kind: string; quantity: number }[], outcomes: WriteContext["outcomes"] = []) {
  const created: { id: EntityId; components: Record<string, unknown> }[] = [], actions: unknown[] = [];
  const rows: QueryRow<object>[] = processes.map(id => ({ id, get: <T extends object>(definition: { id: string }) => ({ [StagedProcess.id]: value(`${id}.station`) }[definition.id] as T) }));
  const containers = [{ id: "source.pail" as EntityId, capacity: 8, sealed: false }, ...processes.map(id => ({ id: `${id}.station:kettle` as EntityId, capacity: 8, sealed: false }))];
  const context: WriteContext = { clock: { now: 0, delta: 1, tick: 0 }, outcomes, random: { next: () => 0 }, impacts: [], query<T extends object>(spec: QuerySpec<T>) { return spec.components.some(c => c.id === StagedProcess.id) ? rows as readonly QueryRow<T>[] : []; }, workMaterialFacts: () => ({ version: 1, containers, lots }), processRequirements: () => req, worldPoses: () => [], routeCosts: () => [], routeToAny: () => ({ actor: "none", status: "unavailable", reason: "test" }), physicalContacts: () => [], environmentFacts: () => null, atmosphereSamples: () => ({ revision: 0, geometryRevision: 0, samples: [] }), constructionReadiness: () => [], constructionAccess: () => [], deconstructionAccess: () => [], terrainMaterials: () => [], terrainSurfaces: () => [], assign: () => [], write: () => {}, action: a => actions.push(a), createAuthoredEntity: r => created.push(r), removeAuthoredEntity: () => {} };
  processSupplyPhase(context); return { created, actions };
}
test("ready port lot admits once without delivery", () => { const r = run(["process.a"], [{ id: "lot", container: "process.a.station:kettle", kind: "grain", quantity: 2 }]); assert.equal(r.created.length, 0); assert.equal(r.actions.length, 1); });
test("missing input creates ordinary unclaimed delivery", () => { const r = run(["process.a"], [{ id: "lot", container: "source.pail", kind: "grain", quantity: 2 }]); assert.equal(r.actions.length, 0); const task = r.created[0]!.components[DeliveryTask.id] as { actor: EntityId | null }; assert.equal(task.actor, null); });
test("competing processes promise source quantity once", () => { const r = run(["process.a", "process.b"], [{ id: "lot", container: "source.pail", kind: "grain", quantity: 2 }]); assert.equal(r.created.reduce((n, x) => n + (x.components[DeliveryTask.id] as { quantity: number }).quantity, 0), 2); });
test("accepted admission is not resubmitted", () => { const r = run(["process.a"], [{ id: "lot", container: "process.a.station:kettle", kind: "grain", quantity: 2 }], [{ action: { kind: "admit-process", process: "process.a", definition: "ale", station: "process.a.station" }, result: { accepted: true, revision: 1 } }]); assert.equal(r.actions.length, 0); });
