import { defineConfig } from "vite";
export default defineConfig({
  server: { host: "127.0.0.1", port: 5187, strictPort: true },
  build: {
    rollupOptions: {
      input: {
        game: "index.html",
        study: "study.html",
        devilStudy: "devil-study.html",
        animalStudy: "animal-study.html",
        fireStudy: "fire-study.html",
        foliageWindStudy: "foliage-wind-study.html",
        brewhouseStudy: "brewhouse-study.html",
        mixedShelfStudy: "mixed-shelf-study.html",
        clearingMinimapStudy: "clearing-minimap-study.html",
        worldLab: "world-lab.html",
        wetClearing: "wet-clearing.html",
        brewhouseAir: "brewhouse-air.html",
        goblinDenStudy: "goblin-den-study.html",
        goblinMessStudy: "goblin-mess-study.html",
        gasHeatLab: "gas-heat-lab.html",
        soilWaterLab: "soil-water-lab.html",
        sloshLab: "slosh-lab.html",
        verticalStudy: "vertical-study.html",
        livingTerrainArt: "living-terrain-art.html",
        engine: "engine/index.html",
        engineColony: "engine/colony.html",
        enginePerformance: "engine/colony-performance.html",
        engineFormations: "engine/formations.html",
        enginePirates: "engine/pirates.html",
        engineSurvival: "engine/survival.html",
        engineMixedRenderReview: "engine/mixed-render-review.html",
      },
    },
  },
});
