//! Durable closed serial job plans. Physical effects and scheduling remain in
//! their existing owners.
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
pub const JOB_VERSION:u8=1; pub const MAX_STEPS:usize=32; pub const MAX_PLAN_BYTES:usize=64*1024;
#[derive(Clone,Debug,PartialEq,Eq,Serialize,Deserialize)]#[serde(rename_all="kebab-case")]pub enum JobDisposition{Active,Cancelled}
#[derive(Clone,Debug,PartialEq,Eq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ResultBinding{pub step:String,pub slot:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",tag="kind",deny_unknown_fields)]pub enum JobOperation{ResourceToItem{source:String,source_kind:String,source_quantity:u32,output_kind:String,output_quantity:u32,work_seconds:f64,result_slot:String},ItemToItems{source:ResultBinding,input_kind:String,input_quantity:u32,output_kind:String,output_quantity:u32,work_seconds:f64,result_slot:String}}
impl JobOperation{fn output(&self)->(&str,u32,&str){match self{Self::ResourceToItem{output_kind,output_quantity,result_slot,..}|Self::ItemToItems{output_kind,output_quantity,result_slot,..}=>(output_kind,*output_quantity,result_slot)}}}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct StepSpec{pub key:String,pub after:Option<String>,pub operation:JobOperation}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct JobPlan{pub definition:String,pub definition_version:u32,pub party:String,pub steps:Vec<StepSpec>}
#[derive(Clone,Debug,PartialEq,Eq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ExactResult{pub slot:String,pub entity:String,pub kind:String,pub quantity:u32}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",tag="kind",content="result",deny_unknown_fields)]pub enum TaskDisposition{Pending,Completed(Vec<ExactResult>),Cancelled}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct TaskRecord{pub id:String,pub key:String,pub after:Option<String>,pub operation:JobOperation,pub disposition:TaskDisposition}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct JobRecord{pub version:u8,pub id:String,pub definition:String,pub definition_version:u32,pub party:String,pub disposition:JobDisposition,pub tasks:BTreeMap<String,TaskRecord>}
fn valid_id(v:&str)->bool{!v.is_empty()&&v.len()<=128&&v.bytes().all(|b|b.is_ascii_alphanumeric()||b"._:-".contains(&b))}
fn task_id(job:&str,key:&str)->Result<String,String>{let id=format!("{job}:task:{key}");valid_id(&id).then_some(id).ok_or("derived task identity exceeds limit".into())}
pub fn admit(id:&str,plan:JobPlan)->Result<JobRecord,String>{if !valid_id(id)||!valid_id(&plan.definition)||!valid_id(&plan.party)||plan.definition_version==0{return Err("invalid job identity or definition".into())}if plan.steps.is_empty()||plan.steps.len()>MAX_STEPS{return Err("job plan step bound exceeded".into())}if serde_json::to_vec(&plan).map_err(|e|e.to_string())?.len()>MAX_PLAN_BYTES{return Err("job plan exceeds byte bound".into())}let keys:BTreeSet<_>=plan.steps.iter().map(|s|s.key.as_str()).collect();if keys.len()!=plan.steps.len()||keys.iter().any(|k|!valid_id(k)){return Err("job step keys must be unique and valid".into())}let mut outputs=BTreeMap::<(&str,&str),(&str,u32)>::new();let mut tasks=BTreeMap::new();for(i,s)in plan.steps.iter().enumerate(){if let Some(a)=&s.after{if !valid_id(a)||!plan.steps[..i].iter().any(|p|p.key==*a){return Err("job dependency must point backward".into())}}validate_operation(&s.operation,s.after.as_deref(),&outputs)?;let tid=task_id(id,&s.key)?;tasks.insert(s.key.clone(),TaskRecord{id:tid,key:s.key.clone(),after:s.after.clone(),operation:s.operation.clone(),disposition:TaskDisposition::Pending});let(k,q,slot)=s.operation.output();if outputs.insert((s.key.as_str(),slot),(k,q)).is_some(){return Err("duplicate result slot".into())}}Ok(JobRecord{version:JOB_VERSION,id:id.into(),definition:plan.definition,definition_version:plan.definition_version,party:plan.party,disposition:JobDisposition::Active,tasks})}
fn validate_operation(op:&JobOperation,after:Option<&str>,outputs:&BTreeMap<(&str,&str),(&str,u32)>)->Result<(),String>{match op{JobOperation::ResourceToItem{source,source_kind,output_kind,source_quantity,output_quantity,work_seconds,result_slot}=>{if !valid_id(source)||!valid_id(source_kind)||!valid_id(output_kind)||!valid_id(result_slot)||*source_quantity==0||*output_quantity==0||!work_seconds.is_finite()||*work_seconds<=0.0{return Err("invalid resource transformation".into())}},JobOperation::ItemToItems{source,input_kind,output_kind,input_quantity,output_quantity,work_seconds,result_slot}=>{let Some((kind,q))=outputs.get(&(source.step.as_str(),source.slot.as_str()))else{return Err("result binding must name an earlier producer".into())};if after!=Some(source.step.as_str())||*kind!=input_kind||*q<*input_quantity||!valid_id(&source.step)||!valid_id(&source.slot)||!valid_id(input_kind)||!valid_id(output_kind)||!valid_id(result_slot)||*input_quantity==0||*output_quantity==0||!work_seconds.is_finite()||*work_seconds<=0.0{return Err("incompatible item transformation".into())}}}Ok(())}
impl JobRecord{pub fn ready(&self,key:&str)->bool{let Some(t)=self.tasks.get(key)else{return false};matches!(t.disposition,TaskDisposition::Pending)&&t.after.as_ref().is_none_or(|a|matches!(self.tasks.get(a).map(|x|&x.disposition),Some(TaskDisposition::Completed(_))))}pub fn complete(&mut self,key:&str,r:Vec<ExactResult>)->Result<(),String>{if !self.ready(key){return Err("task is not ready".into())}let t=self.tasks.get_mut(key).ok_or("unknown task")?;let(k,q,slot)=t.operation.output();if r.len()!=1||r[0].slot!=slot||!valid_id(&r[0].entity)||r[0].kind!=k||r[0].quantity!=q{return Err("task result does not match declared slot".into())}t.disposition=TaskDisposition::Completed(r);Ok(())}pub fn cancel(&mut self){self.disposition=JobDisposition::Cancelled;for t in self.tasks.values_mut(){if matches!(t.disposition,TaskDisposition::Pending){t.disposition=TaskDisposition::Cancelled}}}pub fn validate_restore(&self)->Result<(),String>{if self.version!=JOB_VERSION||!valid_id(&self.id)||!valid_id(&self.definition)||!valid_id(&self.party)||self.tasks.is_empty()||self.tasks.len()>MAX_STEPS{return Err("invalid saved job".into())}for(k,t)in&self.tasks{if k!=&t.key||t.id!=task_id(&self.id,k)?{return Err("saved task identity mismatch".into())}}Ok(())}}
#[cfg(test)]mod tests{use super::*;fn fell()->JobOperation{JobOperation::ResourceToItem{source:"resource".into(),source_kind:"standing".into(),source_quantity:1,output_kind:"trunk".into(),output_quantity:1,work_seconds:3.0,result_slot:"trunk".into()}}fn chop()->JobOperation{JobOperation::ItemToItems{source:ResultBinding{step:"fell".into(),slot:"trunk".into()},input_kind:"trunk".into(),input_quantity:1,output_kind:"log".into(),output_quantity:2,work_seconds:2.0,result_slot:"logs".into()}}fn plan()->JobPlan{JobPlan{definition:"make-logs".into(),definition_version:1,party:"party".into(),steps:vec![StepSpec{key:"fell".into(),after:None,operation:fell()},StepSpec{key:"chop".into(),after:Some("fell".into()),operation:chop()}]}}#[test]fn identity_and_readiness(){let j=admit("job-1",plan()).unwrap();assert_eq!(j.tasks["fell"].id,"job-1:task:fell");assert!(j.ready("fell"));assert!(!j.ready("chop"))}#[test]fn exact_result_unblocks_and_cancel_preserves(){let mut j=admit("job",plan()).unwrap();let r=ExactResult{slot:"trunk".into(),entity:"ground.lot.1".into(),kind:"trunk".into(),quantity:1};j.complete("fell",vec![r.clone()]).unwrap();assert!(j.ready("chop"));j.cancel();assert!(matches!(j.tasks["fell"].disposition,TaskDisposition::Completed(_)));assert_eq!(j.tasks["chop"].disposition,TaskDisposition::Cancelled)}#[test]fn rejects_bad_binding_and_restore_identity(){let mut p=plan();if let JobOperation::ItemToItems{input_kind,..}=&mut p.steps[1].operation{*input_kind="wrong".into()}assert!(admit("job",p).is_err());let mut j=admit("job",plan()).unwrap();j.tasks.get_mut("fell").unwrap().id="resource".into();assert!(j.validate_restore().is_err())}}
