//! Strict authored staged process definitions and native persisted facts.
use bevy_ecs::prelude::Component;
use serde::{Deserialize,Serialize};
use std::collections::{BTreeMap,BTreeSet};
pub const CURRENT_VERSION:u16=1; pub const MAX_STAGES:usize=16;
#[derive(Clone,Copy,Debug,Deserialize,Serialize,PartialEq,Eq)]#[serde(rename_all="lowercase")]pub enum StageMode{Attended,Elapsed}
#[derive(Clone,Copy,Debug,Deserialize,Serialize,PartialEq,Eq)]#[serde(rename_all="lowercase")]pub enum InputPolicy{Portion,WholeLot}
#[derive(Clone,Copy,Debug,Deserialize,Serialize,PartialEq,Eq)]#[serde(rename_all="kebab-case")]pub enum InputDisposition{Consume,Retain,EmissionSource}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessInput{pub role:String,pub port:String,pub material:String,pub quantity:u32,pub policy:InputPolicy,pub disposition:InputDisposition}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessEmission{pub role:String,pub catalog:String}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(tag="kind",rename_all="kebab-case",deny_unknown_fields)]pub enum OutputDestination{StationPort{port:String},RetainedContainer{role:String}}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessOutput{pub role:String,pub material:String,pub quantity:u32,pub destination:OutputDestination}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessTransition{#[serde(default)]pub consume_roles:Vec<String>,pub emission:Option<ProcessEmission>,#[serde(default)]pub outputs:Vec<ProcessOutput>}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessStage{pub id:String,pub mode:StageMode,pub duration_seconds:f64,pub transition:ProcessTransition}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessDefinition{pub id:String,pub station_catalog:String,pub inputs:Vec<ProcessInput>,pub stages:Vec<ProcessStage>}
#[derive(Clone,Debug,PartialEq)]pub struct CompiledProcessDefinition{definition:ProcessDefinition} impl CompiledProcessDefinition{pub fn definition(&self)->&ProcessDefinition{&self.definition}}
#[derive(Clone,Debug,Default,PartialEq)]pub struct ProcessCatalog{definitions:BTreeMap<String,CompiledProcessDefinition>} impl ProcessCatalog{pub fn get(&self,id:&str)->Option<&CompiledProcessDefinition>{self.definitions.get(id)} pub fn len(&self)->usize{self.definitions.len()} pub fn from_definitions(ds:Vec<ProcessDefinition>)->Result<Self,String>{if ds.len()>64{return Err("process catalog exceeds 64 entries".into())}let mut m=BTreeMap::new();for d in ds{let c=compile(d)?;if m.insert(c.definition.id.clone(),c).is_some(){return Err("duplicate process definition id".into())}}Ok(Self{definitions:m})}}
fn valid(s:&str)->bool{!s.is_empty()&&s.len()<=128&&s.bytes().all(|b|b.is_ascii_alphanumeric()||b"._:-".contains(&b))}
pub fn compile(d:ProcessDefinition)->Result<CompiledProcessDefinition,String>{if !valid(&d.id)||!valid(&d.station_catalog)||d.inputs.is_empty()||d.inputs.len()>32||d.stages.is_empty()||d.stages.len()>MAX_STAGES{return Err("invalid process definition bounds or identity".into())}let mut roles=BTreeSet::new();for i in &d.inputs{if !valid(&i.role)||!valid(&i.port)||!valid(&i.material)||i.quantity==0||!roles.insert(i.role.clone()){return Err("invalid or duplicate process input role".into())}}let mut stages=BTreeSet::new();for s in &d.stages{if !valid(&s.id)||!stages.insert(s.id.clone())||!s.duration_seconds.is_finite()||s.duration_seconds<=0.0||s.duration_seconds>86400.0{return Err("invalid process stage".into())}for r in &s.transition.consume_roles{let i=d.inputs.iter().find(|i|i.role==*r).ok_or("unknown consumed role")?;if i.disposition!=InputDisposition::Consume{return Err("transition consumes non-consumable role".into())}}if let Some(e)=&s.transition.emission{let i=d.inputs.iter().find(|i|i.role==e.role).ok_or("unknown emission role")?;if i.disposition!=InputDisposition::EmissionSource||!valid(&e.catalog){return Err("invalid emission source role".into())}}let mut outs=BTreeSet::new();for o in &s.transition.outputs{if !valid(&o.role)||!valid(&o.material)||o.quantity==0||!outs.insert(o.role.clone()){return Err("invalid process output".into())}}}Ok(CompiledProcessDefinition{definition:d})}
#[derive(Component,Clone,Debug,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct StagedProcess{pub definition:String,pub station:String,pub stage_index:u16,pub progress_seconds:f64,pub entered_tick:u64,pub phase:ProcessPhase}
#[derive(Component,Clone,Debug,Serialize,Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]pub struct ProcessBinding{pub process:String,pub role:String,pub lot:String,pub quantity:u32}
#[derive(Clone,Copy,Debug,Serialize,Deserialize)]#[serde(rename_all="lowercase")]pub enum ProcessPhase{Waiting,Working,Blocked,Complete}
#[cfg(test)]mod tests{use super::*;fn fixture()->ProcessDefinition{ProcessDefinition{id:"HERBAL_ALE_V1".into(),station_catalog:"brewery".into(),inputs:vec![ProcessInput{role:"malt".into(),port:"kettle".into(),material:"malt".into(),quantity:2,policy:InputPolicy::Portion,disposition:InputDisposition::Consume}],stages:vec![ProcessStage{id:"prepare".into(),mode:StageMode::Attended,duration_seconds:40.0,transition:ProcessTransition{consume_roles:vec!["malt".into()],emission:None,outputs:vec![]}}]}}#[test]fn valid(){assert!(compile(fixture()).is_ok())}#[test]fn rejects_bad_role(){let mut d=fixture();d.stages[0].transition.consume_roles.push("missing".into());assert!(compile(d).is_err())}}
