import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {restore,serialize,step,edit,metrics} from '../water/solver.mjs';
const here=new URL('./',import.meta.url),solver=new URL('../water/solver.mjs',import.meta.url);
const source=new URL('../water/runs/first-diversion-base/li-divert-no-dig.json',import.meta.url);
const hash=x=>createHash('sha256').update(x).digest('hex');
const solverHash=hash(readFileSync(solver)),sourceHash=hash(readFileSync(source));
const saved=JSON.parse(readFileSync(source,'utf8'));
const old=restore(saved.snapshots.find(s=>Math.abs(s.time-180)<1e-6));
assert.equal(old.events.dig,false);assert(old.V.every(v=>v>=0));assert(metrics(old).pond>20);
const candidate=step(old,.05),dug=edit(old,'dig-pond');
assert.deepEqual(Array.from(dug.V),Array.from(old.V));
const touched=new Set(Array.from(old.geom.region).flatMap((r,i)=>r===4?[i]:[]));
const changedFaces=old.geom.faces.filter(f=>touched.has(f.a)||touched.has(f.b));
const nonzeroReset=changedFaces.filter(f=>old.q[f.id]!==0);
assert(nonzeroReset.length>0);assert(changedFaces.every(f=>dug.q[f.id]===0));
assert.equal(dug.geom.revision,old.geom.revision+1);
const inputFingerprint=hash(JSON.stringify(serialize(old)));
assert.notEqual(hash(JSON.stringify(serialize(dug))),inputFingerprint);
let uninterrupted=dug,resumed=restore(JSON.parse(JSON.stringify(serialize(dug)))),undug=old;
for(let k=0;k<20;k++){
  uninterrupted=step(uninterrupted,.05).state;resumed=step(resumed,.05).state;undug=step(undug,.05).state;
  assert.deepEqual(serialize(uninterrupted),serialize(resumed));
}
const response=uninterrupted.V.reduce((sum,v,i)=>sum+Math.abs(v-undug.V[i]),0);
assert(response>1e-4);assert(Math.abs(metrics(uninterrupted).balanceError)<1e-8);
const bedPotentialDeltaJ=old.V.reduce((total,v,i)=>total+1000*9.81*v*(dug.geom.z[i]-old.geom.z[i]),0);
assert(bedPotentialDeltaJ < -20000);
let target=0;for(let i=1;i<old.V.length;i++)if(candidate.state.V[i]-old.V[i]>candidate.state.V[target]-old.V[target])target=i;
const delta=candidate.state.V[target]-old.V[target];assert(delta>0);
const faces=old.geom.faces.filter(f=>f.a===target||f.b===target).map(f=>({id:f.id,a:f.a,b:f.b,integratedM3:candidate.exchanges[f.id]}));
const receipt={solverSha256:solverHash,initialSnapshotFile:new URL(source).pathname,initialSnapshotSha256:sourceHash,cell:target,oldWaterM3:old.V[target],newWaterM3:candidate.state.V[target],deltaWaterM3:delta,fromTimeSeconds:candidate.interval.start,toTimeSeconds:candidate.interval.end,dtSeconds:candidate.interval.dt,geometryRevision:candidate.interval.geometryRevision,physicalCellAreaM2:old.geom.area,faces,withdrawalM3:candidate.withdrawals[target],assumption:'One receiver replayed into a hypothetical cavity with ideal open exhaust and zero gas backpressure. Snapshot is a prior physical experiment state, not a claim of historical solver replay.'};
let expected=-receipt.withdrawalM3;for(const f of faces)expected+=f.b===target?f.integratedM3:-f.integratedM3;assert(Math.abs(expected-delta)<1e-12);
writeFileSync(new URL('water-receiver-bound.json',here),JSON.stringify(receipt,null,2)+'\n');
assert.equal(solverHash,hash(readFileSync(solver)));
const result={solverSha256:solverHash,initialSnapshotSha256:sourceHash,initialTimeSeconds:old.time,wetPondBeforeM3:metrics(old).pond,wetPondImmediatelyAfterM3:metrics(dug).pond,nonzeroFaceHistoriesExplicitlyReset:nonzeroReset.length,oldRevision:old.geom.revision,newRevision:dug.geom.revision,waterConservedAtEdit:true,restartCompleteTraceExact:true,editedVsUndugAfterOneSecondL1M3:response,bedEditGravitationalPotentialDeltaJ:bedPotentialDeltaJ,balanceErrorM3:metrics(uninterrupted).balanceError,receiver:receipt,limits:'The original no-dig snapshot has nonnegative stock and is used as a new common physical initial condition with the current qualified-for-accounting solver. No claim of reproducing the historical source version, selecting theta.7, or modeling edit dissipation as tracked thermal energy.'};
writeFileSync(new URL(process.argv[2]??'wet-edit-results.json',here),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));
