import {createClearing} from '/tmp/hive-dig-release-dimRCH/src/clearing.ts';
import {snapshotFor} from '/tmp/hive-dig-release-dimRCH/src/persistence.ts';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const snapshot=snapshotFor(createClearing());
assert.equal(snapshot.schema,14);
assert.equal(snapshot.savedState.actors.rowan.rest,80);
assert.equal(snapshot.savedState.materials.lots.filter(x=>x.material==='water').reduce((s,x)=>s+x.quantity,0),8);
await writeFile('/home/levi/src/hive/.botanical/needs/fresh-449e9b8-v14.json',JSON.stringify(snapshot,null,2));
console.log('Actual shipped449e9b8 schema14 fresh snapshot written; rest80/water8 checked.');
