import test from "node:test";
import assert from "node:assert/strict";
import { createMaterialOwner } from "../materials/index.ts";
import { createWorkLifecycle } from "./lifecycle.ts";
const cell={x:0,z:0,level:0};
const access={sourceReachable:true,destinationReachableWithPayload:true};
test("independent finite ore work admission/release is atomic across metadata and physical custody",()=>{
 const materials=createMaterialOwner({ore:{carry:"portion"}});const work=createWorkLifecycle(materials.uses);
 const state=materials.createState(),records=[];
 materials.createGroundLot(state,"ore",5,cell,"ore-a");
 const record={id:"wash",job:"wash-job",definition:"ore-wash"};
 const input={kind:"portion",request:{id:"use",operation:"wash",actor:"miner",lot:"ore-a",material:"ore",quantity:2,access}};
 assert(work.admit(records,state,record,input).ok);
 const before=structuredClone({state,records});
 assert.equal(work.admit(records,state,record,input).ok,false);
 assert.deepEqual({state,records},before);
 assert(materials.pickupTransfer(state,"use",access).ok);
 const held=structuredClone({state,records});
 assert.equal(work.interrupt(records,state,{kind:"release",operation:"wash"}).ok,false);
 assert.deepEqual({state,records},held);
 assert(work.interrupt(records,state,{kind:"release",operation:"wash",drop:{cell,legal:true}}).ok);
 assert.deepEqual(records,[]);assert.deepEqual(state.bindings,[]);assert.deepEqual(state.transfers,[]);
 assert.equal(state.lots.reduce((sum,lot)=>sum+lot.quantity,0),5);
 assert(state.lots.every(lot=>lot.location.kind==="ground"));
});
test("failed material admission creates no orphan work record",()=>{
 const materials=createMaterialOwner({ore:{carry:"portion"}});const state=materials.createState(),records=[];
 const work=createWorkLifecycle(materials.uses);const before=structuredClone(state);
 assert.equal(work.admit(records,state,{id:"wash",job:"job"},{kind:"portion",request:{id:"use",operation:"wash",actor:"miner",lot:"missing",material:"ore",quantity:1,access}}).ok,false);
 assert.deepEqual(records,[]);assert.deepEqual(state,before);
});
