/** Goblin terrain operations and queries all resolve the same generated owner. */
export {
  initialTerrain,
  parseTerrain,
  terrainFacts,
  advanceTerrain,
  excavateTerrain,
  terrainColumn,
  terrainCell,
  terrainDigProblem,
  terrainRevision,
  terrainChangedColumns,
  terrainMaterial,
  terrainGeometry,
  terrainGeometryKey,
  terrainWater,
  terrainExcavatedColumns,
  TERRAIN_FRAME,
  TERRAIN_VOXEL_METRIC,
  voxelSchema,
  GOBLIN_TERRAIN_ID,
} from "./world-presets/goblin-terrain.ts";
