import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root=new URL('./',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root),'utf8'));
const runs=[];for(const dir of readdirSync(new URL('runs/',root))) {try{const m=read(`runs/${dir}/manifest.json`);runs.push({directory:dir,...m});}catch{}}
const get=(dir,name)=>read(`runs/${dir}/${name}.json`),s=(dir,name)=>get(dir,name).summary;
const li=s('first-diversion-base','li-divert-dig'),sw=s('first-diversion-base','swe-divert-dig'),lc=s('first-diversion-base','li-closed'),sc=s('first-diversion-base','swe-closed');
const ref='corrected-refinement',ldt=s(ref,'li-theta0.7-n32-dt0.05'),ldt2=s(ref,'li-theta0.7-n32-dt0.025'),lspace=s(ref,'li-theta0.7-n64-dt0.05');
const corrected=s(ref,'li-theta1-n32-dt0.1'),cdt=s(ref,'li-theta1-n32-dt0.05'),cdt2=s(ref,'li-theta1-n32-dt0.025'),cspace=s(ref,'li-theta1-n64-dt0.05');
const sdt=s(ref,'swe-theta0.7-n32-dt0.05'),sdt2=s(ref,'swe-theta0.7-n32-dt0.025'),sspace=s(ref,'swe-theta0.7-n64-dt0.05');
const rel=(a,b)=>Math.abs(a-b)/Math.max(Math.abs(b),1e-20);
function compare(a,b,volumeTolerance,arrivalFraction,arrivalAbsolute){const pond=rel(a.pond,b.pond),collected=rel(a.collected,b.collected),arrival=Math.abs(a.arrivalSeconds-b.arrivalSeconds),arrivalLimit=Math.max(arrivalAbsolute,arrivalFraction*b.arrivalSeconds);return {pondRelativeDifference:pond,collectedRelativeDifference:collected,arrivalSecondsDifference:arrival,volumeTolerance,arrivalSecondsLimit:arrivalLimit,pass:pond<=volumeTolerance&&collected<=volumeTolerance&&arrival<=arrivalLimit};}
function digComparison(model,dir='first-diversion-base',prefix=model){const dug=get(dir,`${prefix}-divert-dig`),undug=get(dir,`${prefix}-divert-no-dig`),a=dug.snapshots.find(s=>Math.abs(s.time-180)<1e-7),b=undug.snapshots.find(s=>Math.abs(s.time-180)<1e-7);return {maxCellVolumeEditDifference:Math.max(...a.V.map((v,i)=>Math.abs(v-b.V[i]))),geometryBefore:b.geom.revision,geometryAfter:a.geom.revision,pondGainAt600:dug.summary.pond-undug.summary.pond};}
const late=[];for(const model of ['li','swe'])for(const variant of ['closed','divert']){const name=`${model}-${variant}-1200s`,r=get('diagnostic-extended-observation',name);let firstShortage=null;for(let i=1;i<r.trajectory.length;i++){const p=r.trajectory[i-1],q=r.trajectory[i],delivered=q.collected-p.collected,demand=.06*(q.time-p.time);if(p.time>=120&&delivered<demand*.99){firstShortage={start:p.time,end:q.time,delivered,demand};break;}}late.push({name,firstTenSecondIntervalBelow99PercentDemandAfter120s:firstShortage,summary:r.summary});}
const rl32=s('corrected-radial','radial-li-32'),rl64=s('corrected-radial','radial-li-64'),rs32=s('corrected-radial','radial-swe-32'),rs64=s('corrected-radial','radial-swe-64'),rc32=s('corrected-radial-theta1','radial-li-32'),rc64=s('corrected-radial-theta1','radial-li-64');
const orientation=(a,b)=>({coarse:a.relativeRadiusBias,fine:b.relativeRadiusBias,initialVolumes:[a.total,b.total],pass:a.relativeRadiusBias<=.1&&b.relativeRadiusBias<=.1&&b.relativeRadiusBias<a.relativeRadiusBias});
const correctedClosed=s('corrected-corrected-shape','li-theta1-closed'),correctedUndug=s('corrected-corrected-shape','li-theta1-divert-no-dig');
const result={scope:'Bounded authored hydraulic experiment; no selected production solver or game integration',node:process.version,sourceSha256:createHash('sha256').update(readFileSync(new URL('solver.mjs',root))).digest('hex'),
 disposition:{originalThetaPointSeven:'rejected: fixed-grid timestep damping, spatial and original600s behavior fail',thetaOneCorrection:'retained candidate: bulk/dt/spatial checks improve; radial bias decrease fails; rapid-flow applicability remains unqualified',fullSwe:'qualified reference for tested rest/Ritter cases and serious next candidate; no external2D calibration or arbitrary gate/steep-bed validation',groundwater:'reject total-only bucket as sufficient for reversed seepage; no Richards integration proof',productionAccepted:false},
 balances:{originalLI:li,originalSWE:sw,correctedLI:corrected},
 checks:{
 originalBehavior:{pondGain:li.pond,collectionReduction:1-li.collected/lc.collected,sourceFractionDepleted:1-li.reservoir/115.2,pass:li.pond>=10&&li.collected<=.9*lc.collected&&li.reservoir<=.75*115.2},
 sweBehavior:{pondGain:sw.pond,collectionReduction:1-sw.collected/sc.collected,sourceFractionDepleted:1-sw.reservoir/115.2,pass:sw.pond>=10&&sw.collected<=.9*sc.collected&&sw.reservoir<=.75*115.2},
 correctedBehavior:{pondGain:corrected.pond,collectionReduction:1-corrected.collected/correctedClosed.collected,sourceFractionDepleted:1-corrected.reservoir/115.2,digPondGain:corrected.pond-correctedUndug.pond,pass:corrected.pond>=10&&corrected.collected<=.9*correctedClosed.collected&&corrected.reservoir<=.75*115.2&&corrected.pond-correctedUndug.pond>=1},
 originalDt:compare(ldt,ldt2,.05,.1,2),correctedDt:compare(cdt,cdt2,.05,.1,2),sweDt:compare(sdt,sdt2,.05,.1,2),
 originalSpace:compare(ldt,lspace,.15,.2,4),correctedSpace:compare(cdt,cspace,.15,.2,4),sweSpace:compare(sdt,sspace,.15,.2,4),
 originalVersusSwe:compare(li,sw,.15,.2,4),correctedVersusSweFineDt:compare(cdt2,sdt2,.15,.2,4),
 radial:{original:orientation(rl32,rl64),corrected:orientation(rc32,rc64),swe:orientation(rs32,rs64)},
 wetEdit:{li:digComparison('li'),swe:digComparison('swe')},
 restart:{li:s('corrected-restart','restart-li'),swe:s('corrected-restart','restart-swe')},
 rotation90:{li:s('corrected-restart','rotation90-li'),swe:s('corrected-restart','rotation90-swe')},
 referenceQualification:{sweHalfMetre:s('initial-qualification','ritter-swe-64').normalizedDepthL1,sweQuarterMetre:s('initial-qualification','ritter-swe-128').normalizedDepthL1,liHalfMetre:s('initial-qualification','ritter-li-64').normalizedDepthL1,liQuarterMetre:s('initial-qualification','ritter-li-128').normalizedDepthL1},
 },demandCapDiagnostic:late,costs:{li:s('bounded-cost-li','cost-li').cost,swe:s('bounded-cost-swe','cost-swe').cost,liElapsedMs:get('bounded-cost-li','cost-li').elapsedMs,sweElapsedMs:get('bounded-cost-swe','cost-swe').elapsedMs},groundwater:read('groundwater-results.json'),
 exactLocalCharacteristicBoundary:[.1,.5,1,2].map(Fr=>({Fr,localInertialWaveSpeedsOverSqrtGH:[-1,1],fullSweWaveSpeedsOverSqrtGH:[Fr-1,Fr+1],rightGoingRelativeSpeedError:Fr/(Fr+1)})),
 limitations:['No calibrated gate contraction/submergence, hydraulic jump, pressure pipe, vertical waterfall or3D flow','Rusanov first-order reference has numerical diffusion; hydrostatic reconstruction can misbehave on steep shallow beds','LI Froude reconstructed on faces; SWE on cells; no directmax-velocity equivalence','LI withdrawal shares old donor budget; SWE withdrawal is a later positivity-preserving source operator; splitting differs and is checked bydt refinement','No joint mechanical/thermal energy ledger: bed excavation and friction/momentum reset have explicit unmodeled work/heat','No browser/game/population, planetary/offline/distributed or production-memory capacity claim'],runs};
writeFileSync(new URL('results.json',root),JSON.stringify(result,null,2)+'\n');
const rows=[['LI theta=.7 dt=.1',li],['LI theta=.7 dt=.05',ldt],['LI theta=.7 dt=.025',ldt2],['LI theta=1 dt=.1',corrected],['LI theta=1 dt=.05',cdt],['LI theta=1 dt=.025',cdt2],['SWE dt=.1',sw],['SWE dt=.05',sdt],['SWE dt=.025',sdt2]];
writeFileSync(new URL('comparison.csv',root),'method,pond_m3,collected_m3,arrival_s\n'+rows.map(([name,r])=>`${name},${r.pond},${r.collected},${r.arrivalSeconds}`).join('\n')+'\n');
console.log(JSON.stringify({disposition:result.disposition,checks:result.checks,demandCapDiagnostic:late.map(({name,firstTenSecondIntervalBelow99PercentDemandAfter120s})=>({name,firstTenSecondIntervalBelow99PercentDemandAfter120s})),runs:runs.length},null,2));
